git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

# Do not pause after closing external tools like merge tools
promptToReturnFromSubprocess: false
promptToOpenMergeTool: false

gui:
  scrollHeight: 0

keybinding:
  universal:
    undo: u
