git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

# Do not pause after closing external tools like merge tools
promptToReturnFromSubprocess: false
promptToOpenMergeTool: false

gui:
  scrollHeight: 32
  scrollPastBottom: false
  scrollOffMargin: 8
  scrollOffBehavior: margin

keybinding:
  universal:
    undo: u
