# Custom keymap for Yazi mirroring VS Code Explorer shortcuts
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Operations
  { on = "<Esc>", run = "quit", desc = "Close Yazi" },
	# { on = "s",         run = "open",                        desc = "Open selected files" },
	# { on = "S",         run = "open --interactive",          desc = "Open selected files interactively" },
	{ on = "x",         run = "yank --cut",                  desc = "Yank selected files (cut)" },
	{ on = "d",         run = "remove",                      desc = "Trash selected files" },
	{ on = "D",         run = "remove --permanently",        desc = "Permanently delete selected files" },
	{ on = "o",         run = "create",                      desc = "Create a file (ends with / for directories)" },
	{ on = "i",         run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" },
	{ on = ["<Space>", "<Space>"], run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = ["<Space>", "s", "f"], run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = ["<Space>", "s", "t"],         run = "search --via=rg",             desc = "Search files by content via ripgrep" },
	{ on = "<Backspace>", run = [ "toggle", "arrow next" ], desc = "Toggle the current selection state" },#

  # Shortcuts
	{ on = "<D-f>", run = "find --smart",            desc = "Find next file" },
	{ on = "<S-D-f>",         run = "search --via=rg",             desc = "Search files by content via ripgrep" },

  # Macros
	{ on = "<S-F3>", run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = "<S-F4>", run = "arrow -50%",  desc = "Move cursor up half page" },
	{ on = "<S-F6>", run = "arrow 50%",   desc = "Move cursor down half page" },

  { on = [ "0" ], run = "plugin relative-line-numbers 0", desc = "Jump (starts with 0)" },
  { on = [ "1" ], run = "plugin relative-line-numbers 1", desc = "Jump (starts with 1)" },
  { on = [ "2" ], run = "plugin relative-line-numbers 2", desc = "Jump (starts with 2)" },
  { on = [ "3" ], run = "plugin relative-line-numbers 3", desc = "Jump (starts with 3)" },
  { on = [ "4" ], run = "plugin relative-line-numbers 4", desc = "Jump (starts with 4)" },
  { on = [ "5" ], run = "plugin relative-line-numbers 5", desc = "Jump (starts with 5)" },
  { on = [ "6" ], run = "plugin relative-line-numbers 6", desc = "Jump (starts with 6)" },
  { on = [ "7" ], run = "plugin relative-line-numbers 7", desc = "Jump (starts with 7)" },
  { on = [ "8" ], run = "plugin relative-line-numbers 8", desc = "Jump (starts with 8)" },
  { on = [ "9" ], run = "plugin relative-line-numbers 9", desc = "Jump (starts with 9)" },

  # Optional helper key – lets you type e.g. “m 4 2 j”
  { on = [ "m" ], run = "plugin relative-line-numbers", desc = "Start relative jump" }
  # Vim style numeric jumps

  # # -- Move Down (j)
  # { on = ["2", "j"], run = "arrow 2", hidden=true },
  # { on = ["3", "j"], run = "arrow 3", hidden=true },
  # { on = ["4", "j"], run = "arrow 4", hidden=true },
  # { on = ["5", "j"], run = "arrow 5", hidden=true },
  # { on = ["6", "j"], run = "arrow 6", hidden=true },
  # { on = ["7", "j"], run = "arrow 7", hidden=true },
  # { on = ["8", "j"], run = "arrow 8", hidden=true },
  # { on = ["9", "j"], run = "arrow 9", hidden=true },
  # { on = ["1", "0", "j"], run = "arrow 10", hidden=true },
  # { on = ["1", "1", "j"], run = "arrow 11", hidden=true },
  # { on = ["1", "2", "j"], run = "arrow 12", hidden=true },
  # { on = ["1", "3", "j"], run = "arrow 13", hidden=true },
  # { on = ["1", "4", "j"], run = "arrow 14", hidden=true },
  # { on = ["1", "5", "j"], run = "arrow 15", hidden=true },
  # { on = ["1", "6", "j"], run = "arrow 16", hidden=true },
  # { on = ["1", "7", "j"], run = "arrow 17", hidden=true },
  # { on = ["1", "8", "j"], run = "arrow 18", hidden=true },
  # { on = ["1", "9", "j"], run = "arrow 19", hidden=true },
  # { on = ["2", "0", "j"], run = "arrow 20", hidden=true },
  # { on = ["2", "1", "j"], run = "arrow 21", hidden=true },
  # { on = ["2", "2", "j"], run = "arrow 22", hidden=true },
  # { on = ["2", "3", "j"], run = "arrow 23", hidden=true },
  # { on = ["2", "4", "j"], run = "arrow 24", hidden=true },
  # { on = ["2", "5", "j"], run = "arrow 25", hidden=true },
  # { on = ["2", "6", "j"], run = "arrow 26", hidden=true },
  # { on = ["2", "7", "j"], run = "arrow 27", hidden=true },
  # { on = ["2", "8", "j"], run = "arrow 28", hidden=true },
  # { on = ["2", "9", "j"], run = "arrow 29", hidden=true },
  # { on = ["3", "0", "j"], run = "arrow 30", hidden=true },
  # { on = ["3", "1", "j"], run = "arrow 31", hidden=true },
  # { on = ["3", "2", "j"], run = "arrow 32", hidden=true },
  # { on = ["3", "3", "j"], run = "arrow 33", hidden=true },
  # { on = ["3", "4", "j"], run = "arrow 34", hidden=true },
  # { on = ["3", "5", "j"], run = "arrow 35", hidden=true },
  # { on = ["3", "6", "j"], run = "arrow 36", hidden=true },
  # { on = ["3", "7", "j"], run = "arrow 37", hidden=true },
  # { on = ["3", "8", "j"], run = "arrow 38", hidden=true },
  # { on = ["3", "9", "j"], run = "arrow 39", hidden=true },
  # { on = ["4", "0", "j"], run = "arrow 40", hidden=true },
  # { on = ["4", "1", "j"], run = "arrow 41", hidden=true },
  # { on = ["4", "2", "j"], run = "arrow 42", hidden=true },
  # { on = ["4", "3", "j"], run = "arrow 43", hidden=true },
  # { on = ["4", "4", "j"], run = "arrow 44", hidden=true },
  # { on = ["4", "5", "j"], run = "arrow 45", hidden=true },
  # { on = ["4", "6", "j"], run = "arrow 46", hidden=true },
  # { on = ["4", "7", "j"], run = "arrow 47", hidden=true },
  # { on = ["4", "8", "j"], run = "arrow 48", hidden=true },
  # { on = ["4", "9", "j"], run = "arrow 49", hidden=true },
  # { on = ["5", "0", "j"], run = "arrow 50", hidden=true },
  # { on = ["5", "1", "j"], run = "arrow 51", hidden=true },
  # { on = ["5", "2", "j"], run = "arrow 52", hidden=true },
  # { on = ["5", "3", "j"], run = "arrow 53", hidden=true },
  # { on = ["5", "4", "j"], run = "arrow 54", hidden=true },
  # { on = ["5", "5", "j"], run = "arrow 55", hidden=true },
  # { on = ["5", "6", "j"], run = "arrow 56", hidden=true },
  # { on = ["5", "7", "j"], run = "arrow 57", hidden=true },
  # { on = ["5", "8", "j"], run = "arrow 58", hidden=true },
  # { on = ["5", "9", "j"], run = "arrow 59", hidden=true },
  # { on = ["6", "0", "j"], run = "arrow 60", hidden=true },
  # { on = ["6", "1", "j"], run = "arrow 61", hidden=true },
  # { on = ["6", "2", "j"], run = "arrow 62", hidden=true },
  # { on = ["6", "3", "j"], run = "arrow 63", hidden=true },
  # { on = ["6", "4", "j"], run = "arrow 64", hidden=true },
  # { on = ["6", "5", "j"], run = "arrow 65", hidden=true },
  # { on = ["6", "6", "j"], run = "arrow 66", hidden=true },
  # { on = ["6", "7", "j"], run = "arrow 67", hidden=true },
  # { on = ["6", "8", "j"], run = "arrow 68", hidden=true },
  # { on = ["6", "9", "j"], run = "arrow 69", hidden=true },
  # { on = ["7", "0", "j"], run = "arrow 70", hidden=true },
  # { on = ["7", "1", "j"], run = "arrow 71", hidden=true },
  # { on = ["7", "2", "j"], run = "arrow 72", hidden=true },
  # { on = ["7", "3", "j"], run = "arrow 73", hidden=true },
  # { on = ["7", "4", "j"], run = "arrow 74", hidden=true },
  # { on = ["7", "5", "j"], run = "arrow 75", hidden=true },
  # { on = ["7", "6", "j"], run = "arrow 76", hidden=true },
  # { on = ["7", "7", "j"], run = "arrow 77", hidden=true },
  # { on = ["7", "8", "j"], run = "arrow 78", hidden=true },
  # { on = ["7", "9", "j"], run = "arrow 79", hidden=true },
  # { on = ["8", "0", "j"], run = "arrow 80", hidden=true },
  # { on = ["8", "1", "j"], run = "arrow 81", hidden=true },
  # { on = ["8", "2", "j"], run = "arrow 82", hidden=true },
  # { on = ["8", "3", "j"], run = "arrow 83", hidden=true },
  # { on = ["8", "4", "j"], run = "arrow 84", hidden=true },
  # { on = ["8", "5", "j"], run = "arrow 85", hidden=true },
  # { on = ["8", "6", "j"], run = "arrow 86", hidden=true },
  # { on = ["8", "7", "j"], run = "arrow 87", hidden=true },
  # { on = ["8", "8", "j"], run = "arrow 88", hidden=true },
  # { on = ["8", "9", "j"], run = "arrow 89", hidden=true },
  # { on = ["9", "0", "j"], run = "arrow 90", hidden=true },
  # { on = ["9", "1", "j"], run = "arrow 91", hidden=true },
  # { on = ["9", "2", "j"], run = "arrow 92", hidden=true },
  # { on = ["9", "3", "j"], run = "arrow 93", hidden=true },
  # { on = ["9", "4", "j"], run = "arrow 94", hidden=true },
  # { on = ["9", "5", "j"], run = "arrow 95", hidden=true },
  # { on = ["9", "6", "j"], run = "arrow 96", hidden=true },
  # { on = ["9", "7", "j"], run = "arrow 97", hidden=true },
  # { on = ["9", "8", "j"], run = "arrow 98", hidden=true },
  # { on = ["9", "9", "j"], run = "arrow 99", hidden=true },
  #
  # # -- Move Up (k)
  # { on = ["2", "k"], run = "arrow -2", hidden=true },
  # { on = ["3", "k"], run = "arrow -3", hidden=true },
  # { on = ["4", "k"], run = "arrow -4", hidden=true },
  # { on = ["5", "k"], run = "arrow -5", hidden=true },
  # { on = ["6", "k"], run = "arrow -6", hidden=true },
  # { on = ["7", "k"], run = "arrow -7", hidden=true },
  # { on = ["8", "k"], run = "arrow -8", hidden=true },
  # { on = ["9", "k"], run = "arrow -9", hidden=true },
  # { on = ["1", "0", "k"], run = "arrow -10", hidden=true },
  # { on = ["1", "1", "k"], run = "arrow -11", hidden=true },
  # { on = ["1", "2", "k"], run = "arrow -12", hidden=true },
  # { on = ["1", "3", "k"], run = "arrow -13", hidden=true },
  # { on = ["1", "4", "k"], run = "arrow -14", hidden=true },
  # { on = ["1", "5", "k"], run = "arrow -15", hidden=true },
  # { on = ["1", "6", "k"], run = "arrow -16", hidden=true },
  # { on = ["1", "7", "k"], run = "arrow -17", hidden=true },
  # { on = ["1", "8", "k"], run = "arrow -18", hidden=true },
  # { on = ["1", "9", "k"], run = "arrow -19", hidden=true },
  # { on = ["2", "0", "k"], run = "arrow -20", hidden=true },
  # { on = ["2", "1", "k"], run = "arrow -21", hidden=true },
  # { on = ["2", "2", "k"], run = "arrow -22", hidden=true },
  # { on = ["2", "3", "k"], run = "arrow -23", hidden=true },
  # { on = ["2", "4", "k"], run = "arrow -24", hidden=true },
  # { on = ["2", "5", "k"], run = "arrow -25", hidden=true },
  # { on = ["2", "6", "k"], run = "arrow -26", hidden=true },
  # { on = ["2", "7", "k"], run = "arrow -27", hidden=true },
  # { on = ["2", "8", "k"], run = "arrow -28", hidden=true },
  # { on = ["2", "9", "k"], run = "arrow -29", hidden=true },
  # { on = ["3", "0", "k"], run = "arrow -30", hidden=true },
  # { on = ["3", "1", "k"], run = "arrow -31", hidden=true },
  # { on = ["3", "2", "k"], run = "arrow -32", hidden=true },
  # { on = ["3", "3", "k"], run = "arrow -33", hidden=true },
  # { on = ["3", "4", "k"], run = "arrow -34", hidden=true },
  # { on = ["3", "5", "k"], run = "arrow -35", hidden=true },
  # { on = ["3", "6", "k"], run = "arrow -36", hidden=true },
  # { on = ["3", "7", "k"], run = "arrow -37", hidden=true },
  # { on = ["3", "8", "k"], run = "arrow -38", hidden=true },
  # { on = ["3", "9", "k"], run = "arrow -39", hidden=true },
  # { on = ["4", "0", "k"], run = "arrow -40", hidden=true },
  # { on = ["4", "1", "k"], run = "arrow -41", hidden=true },
  # { on = ["4", "2", "k"], run = "arrow -42", hidden=true },
  # { on = ["4", "3", "k"], run = "arrow -43", hidden=true },
  # { on = ["4", "4", "k"], run = "arrow -44", hidden=true },
  # { on = ["4", "5", "k"], run = "arrow -45", hidden=true },
  # { on = ["4", "6", "k"], run = "arrow -46", hidden=true },
  # { on = ["4", "7", "k"], run = "arrow -47", hidden=true },
  # { on = ["4", "8", "k"], run = "arrow -48", hidden=true },
  # { on = ["4", "9", "k"], run = "arrow -49", hidden=true },
  # { on = ["5", "0", "k"], run = "arrow -50", hidden=true },
  # { on = ["5", "1", "k"], run = "arrow -51", hidden=true },
  # { on = ["5", "2", "k"], run = "arrow -52", hidden=true },
  # { on = ["5", "3", "k"], run = "arrow -53", hidden=true },
  # { on = ["5", "4", "k"], run = "arrow -54", hidden=true },
  # { on = ["5", "5", "k"], run = "arrow -55", hidden=true },
  # { on = ["5", "6", "k"], run = "arrow -56", hidden=true },
  # { on = ["5", "7", "k"], run = "arrow -57", hidden=true },
  # { on = ["5", "8", "k"], run = "arrow -58", hidden=true },
  # { on = ["5", "9", "k"], run = "arrow -59", hidden=true },
  # { on = ["6", "0", "k"], run = "arrow -60", hidden=true },
  # { on = ["6", "1", "k"], run = "arrow -61", hidden=true },
  # { on = ["6", "2", "k"], run = "arrow -62", hidden=true },
  # { on = ["6", "3", "k"], run = "arrow -63", hidden=true },
  # { on = ["6", "4", "k"], run = "arrow -64", hidden=true },
  # { on = ["6", "5", "k"], run = "arrow -65", hidden=true },
  # { on = ["6", "6", "k"], run = "arrow -66", hidden=true },
  # { on = ["6", "7", "k"], run = "arrow -67", hidden=true },
  # { on = ["6", "8", "k"], run = "arrow -68", hidden=true },
  # { on = ["6", "9", "k"], run = "arrow -69", hidden=true },
  # { on = ["7", "0", "k"], run = "arrow -70", hidden=true },
  # { on = ["7", "1", "k"], run = "arrow -71", hidden=true },
  # { on = ["7", "2", "k"], run = "arrow -72", hidden=true },
  # { on = ["7", "3", "k"], run = "arrow -73", hidden=true },
  # { on = ["7", "4", "k"], run = "arrow -74", hidden=true },
  # { on = ["7", "5", "k"], run = "arrow -75", hidden=true },
  # { on = ["7", "6", "k"], run = "arrow -76", hidden=true },
  # { on = ["7", "7", "k"], run = "arrow -77", hidden=true },
  # { on = ["7", "8", "k"], run = "arrow -78", hidden=true },
  # { on = ["7", "9", "k"], run = "arrow -79", hidden=true },
  # { on = ["8", "0", "k"], run = "arrow -80", hidden=true },
  # { on = ["8", "1", "k"], run = "arrow -81", hidden=true },
  # { on = ["8", "2", "k"], run = "arrow -82", hidden=true },
  # { on = ["8", "3", "k"], run = "arrow -83", hidden=true },
  # { on = ["8", "4", "k"], run = "arrow -84", hidden=true },
  # { on = ["8", "5", "k"], run = "arrow -85", hidden=true },
  # { on = ["8", "6", "k"], run = "arrow -86", hidden=true },
  # { on = ["8", "7", "k"], run = "arrow -87", hidden=true },
  # { on = ["8", "8", "k"], run = "arrow -88", hidden=true },
  # { on = ["8", "9", "k"], run = "arrow -89", hidden=true },
  # { on = ["9", "0", "k"], run = "arrow -90", hidden=true },
  # { on = ["9", "1", "k"], run = "arrow -91", hidden=true },
  # { on = ["9", "2", "k"], run = "arrow -92", hidden=true },
  # { on = ["9", "3", "k"], run = "arrow -93", hidden=true },
  # { on = ["9", "4", "k"], run = "arrow -94", hidden=true },
  # { on = ["9", "5", "k"], run = "arrow -95", hidden=true },
  # { on = ["9", "6", "k"], run = "arrow -96", hidden=true },
  # { on = ["9", "7", "k"], run = "arrow -97", hidden=true },
  # { on = ["9", "8", "k"], run = "arrow -98", hidden=true },
  # { on = ["9", "9", "k"], run = "arrow -99", hidden=true },
]
