# Custom keymap for Yazi mirroring VS Code Explorer shortcuts
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  # Close Yazi similar to toggling the Explorer
  { on = "<Esc>", run = "quit", desc = "Close Yazi" },
  { on = "e",     run = "quit", desc = "Close Yazi" },

  # File operations from VS Code Explorer
	{ on = "g",         run = "open",                        desc = "Open selected files" },
	{ on = "G",         run = "open --interactive",          desc = "Open selected files interactively" },
	{ on = "x",         run = "yank --cut",                  desc = "Yank selected files (cut)" },
	{ on = "d",         run = "remove",                      desc = "Trash selected files" },
	{ on = "D",         run = "remove --permanently",        desc = "Permanently delete selected files" },
	{ on = "o",         run = "create",                      desc = "Create a file (ends with / for directories)" },
	{ on = "i",         run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" },
	{ on = ["<Space>", "<Space>"], run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = ["<S-F3>"], run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = ["<Space>", "s", "f"], run = "search --via=fd",             desc = "Search files by name via fd" },
	{ on = "D-S-f",         run = "search --via=rg",             desc = "Search files by content via ripgrep" },
	{ on = ["<Space>", "s", "t"],         run = "search --via=rg",             desc = "Search files by content via ripgrep" },
	{ on = "D-f", run = "find --smart",            desc = "Find next file" },
	{ on = "<Backspace>", run = [ "toggle", "arrow next" ], desc = "Toggle the current selection state" },#
	{ on = "<S-F4>", run = "arrow -50%",  desc = "Move cursor up half page" },
	{ on = "<S-F6>", run = "arrow 50%",   desc = "Move cursor down half page" },
]
