git:
  paging:
    # Delta wants colored input; LazyGit handles paging itself
    colorArg: always # recommended for delta as a pager
    pager: delta --dark --paging=never \
      --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  parseEmoji: false

promptToReturnFromSubprocess: false
promptToOpenMergeTool: false
scrollOffBehavior: margin

os:
  editPreset: nvim
  open: "code --reuse-window {{filename}}"
  openDirInEditor: "code --reuse-window {{dir}}"

gui:
  scrollHeight: 32
  scrollPastBottom: false
  scrollOffMargin: 8
  nerdFontsVersion: "3"
  showFileIcons: true
  theme:
    lightTheme: false
    # Tokyo Night Moon-ish accents
    activeBorderColor: ["#82aaff"]
    inactiveBorderColor: ["#444a73"]
    selectedLineBgColor: ["#2d3f76"]
    optionsTextColor: ["#ffc777"]
    defaultFgColor: ["#c8d3f5"]

keybinding:
  universal:
    undo: u
