name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Ensure chezmoi is installed (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if ! command -v chezmoi >/dev/null; then
            echo "chezmoi not found. Attempting to install"
            if command -v apt-get >/dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y chezmoi || \
                sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
            elif command -v brew >/dev/null; then
              brew install chezmoi
            else
              sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
            fi
          fi

      - name: Ensure chezmoi is installed (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (-not (Get-Command chezmoi -ErrorAction SilentlyContinue)) {
            choco install -y chezmoi
          }

      - name: Dry-run apply
        run: chezmoi apply --dry-run -S .

      - name: Doctor
        run: chezmoi doctor -S .

  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update -y && sudo apt-get install -y shellcheck

      - name: Shellcheck
        run: |
          find . -name '*.sh' -print | xargs -r shellcheck

      # Use the official Stylua action instead of apt
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Pin to a specific version to avoid formatting drift
          version: 2.1.0
          # Check all Neovim Lua files
          args: --check dot_config/nvim
