name: CI
on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install stow and dry-run (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          set -euxo pipefail
          if command -v apt-get >/dev/null; then
            sudo apt-get update -y && sudo apt-get install -y stow
          elif command -v brew >/dev/null; then
            brew install stow
          elif command -v dnf >/dev/null; then
            sudo dnf install -y stow
          elif command -v pacman >/dev/null; then
            sudo pacman -Sy --noconfirm stow
          fi
          # Preview stow into a temp HOME
          TARGET="$RUNNER_TEMP/home"
          mkdir -p "$TARGET"
          stow -d stow -t "$TARGET" -n -v zsh ripgrep shell fzf local-bin kitty wezterm lazygit helix bat hammerspoon nvim

      - name: Windows bootstrap what-if
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./scripts/bootstrap.ps1 -WhatIf
