name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
      - name: Dry-run apply
        run: chezmoi apply --dry-run -S .
      - name: Doctor
        run: chezmoi doctor -S .
