git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  parseEmoji: false

promptToReturnFromSubprocess: false
promptToOpenMergeTool: false

os:
  editPreset: nvim
  open: "code --reuse-window {{filename}}"
  openDirInEditor: "code --reuse-window {{dir}}"

gui:
  scrollHeight: 32
  scrollPastBottom: false
  scrollOffMargin: 8
  scrollOffBehavior: margin

keybinding:
  universal:
    undo: u
